
[site]
url = "http://localhost"
name = "climabc"
description = "IPCC气候报告中文化Zine"
# logo = "/path/to/favicon"
locale = "zh"

[[issue]]
slug = "index"
number = 1
title = "卷首"
path = "content/index"

[[issue]]
slug = "ipcc-wg1-faq"
number = 3
title = "IPCC第1工作组FAQ"
path = "content/ipcc/wg-1/faq"
