
[site]
url = "http://localhost"
name = "climabc"
description = ""
# logo = "/path/to/favicon"
locale = "zh"

[[issue]]
slug = "s1"
number = 1
title = "卷首"
path = "content/index"
# intro = "content/issue-1/intro.md

[[issue]]
slug = "ipcc"
number = 2
title = "IPCC第1工作组FAQ"
path = "content/ipcc/wg-1/faq"
