
[[article]]
slug = "faq1-1"
file = "1-1.md"
title = "IPCC第1工作组 - FAQ 1.1"
author = "blizhan"
cover = "/static/ipcc/wg-1/FAQ1-1.png"
pub_date = "2022-08-29"
publish = true
featured = true

[[article]]
slug = "faq1-2"
file = "1-2.md"
title = "IPCC第1工作组 - FAQ 1.2"
author = "blizhan"
cover = "/static/ipcc/wg-1/FAQ1-2.png"
pub_date = "2022-09-01"
publish = true
featured = true

[[article]]
slug = "faq1-3"
file = "1-3.md"
title = "IPCC第1工作组 - FAQ 1.3"
author = "blizhan"
cover = "/static/ipcc/wg-1/FAQ1-3.png"
pub_date = "2022-09-04"
publish = true
featured = true